# Generated by Django 3.2.6 on 2021-12-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='title',
            field=models.CharField(max_length=40, verbose_name='Başlıq'),
        ),
    ]
