# Generated by Django 3.2.6 on 2021-10-02 13:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_nama_surname_contactmodel_name_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='files',
            field=models.FileField(default='Null', upload_to='files', verbose_name='Fayl'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='categories',
            field=models.ManyToManyField(related_name='article', to='blog.CategoryModel', verbose_name='Kateqoriyalar'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Məzmun'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='image',
            field=models.ImageField(upload_to='article_image', verbose_name='Şəkil'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Başlıq'),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='comment',
            field=models.TextField(verbose_name='Şərh'),
        ),
    ]
