# Generated by Django 3.2.6 on 2021-10-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20211002_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='files',
            field=models.FileField(upload_to='files', verbose_name='Fayl'),
        ),
    ]
