# Generated by Django 3.2.6 on 2021-10-05 15:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_articlemodel_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlemodel',
            name='image',
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Açıqlama'),
        ),
    ]
