# Generated by Django 3.2.6 on 2021-10-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20211005_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='files', verbose_name='Fayl'),
        ),
    ]
