# Generated by Django 3.2.6 on 2021-10-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_articlemodel_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='files',
            field=models.FileField(upload_to='files', verbose_name='Fayl'),
        ),
    ]
