# Generated by Django 3.2.6 on 2021-10-08 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_articlemodel_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='title',
            field=models.CharField(max_length=15, verbose_name='Başlıq'),
        ),
    ]
