# Generated by Django 3.2.6 on 2021-10-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_articlemodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='title',
            field=models.CharField(max_length=17, verbose_name='Başlıq'),
        ),
    ]
