from .contact import contact
from .homepage import homePage
from .category import category
from .myarticles import myArticles
from .detail import detail
from .add_article import add_article
from .update_article import update_article
from .delete_article import delete_article
from .delete_comment import delete_comment