from .contact import ContactFormView
from .homepage import homePage
from .category import CategoryListView
from .myarticles import myArticles
from .detail import DetailView
from .add_article import AddArticleCreateView
from .update_article import UpdateArticleUpdateView
from .delete_article import ArticleDeleteView
from .delete_comment import delete_comment