from .contact import contact
from .homepage import homePage
from .category import CategoryListView
from .myarticles import myArticles
from .detail import DetailView
from .add_article import add_article
from .update_article import update_article
from .delete_article import ArticleDeleteView
from .delete_comment import delete_comment